name: Test and Deploy ETL Pipeline

on:
  push:
    branches:
      - master

jobs:
  #test:
  #  runs-on: ubuntu-latest

  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2

      #- name: Set up Python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: '3.8'

      #- name: Install dependencies
      #  run: |
      #    pip install -r requirements.txt
      #    pip install pytest

      #- name: Run Tests
      #  run: pytest test_etl.py

  deploy:
    runs-on: ubuntu-latest
    #needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Init Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false
        env:
          TF_LOG: DEBUG
